[tool.mypy]
check_untyped_defs = true
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
exclude = [
    'migrations/\d{4}_merge_.*', # merge migrations
]

[tool.django-stubs]
django_settings_module = "domain.settings"

[tool.black]
# Do not run black on migrations
extend-exclude = '''
/migrations/\d{4}_.*.py
'''
