# Generated by Django 4.2.1 on 2023-05-09 16:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatapoint",
            name="definition",
            field=models.JSONField(default=main.models.get_default_translation_json),
        ),
        migrations.AlterField(
            model_name="masterdatapoint",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
